### ISSUE TITLE
Cannot export theme on RF4.3 on Monterey

### ISSUE THREAD

**Issue by vennjadin** [connordavenport/Theme-Manager#11]
Traceback:

```
/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/py23.py:6: DeprecationWarning: The py23 module has been deprecated and will be removed. Please update your code.
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 514, in action_
    self.callback(sender)
  File "ThemeManager.py", line 387, in exportThemeCallback
NameError: name 'plistPath' is not defined
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 84, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 514, in action_
    self.callback(sender)
  File "ThemeManager.py", line 387, in exportThemeCallback
NameError: name 'plistPath' is not defined
```

**Comment by connordavenport** [comment]
Hi @vennjadin , thanks for reporting this. I have pushed an update which should fix this!
