### ISSUE TITLE
ThemeManager not opening in RF v4.4b (build 2305191108)

### ISSUE THREAD

**Issue by opr-inzn** [connordavenport/Theme-Manager#14]
```
Traceback (most recent call last):
  File "ThemeManager.py", line 635, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 52, in OpenWindow
  File "ThemeManager.py", line 156, in __init__
  File "ThemeManager.py", line 551, in makeBackupTheme
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by connordavenport** [comment]
Hi @opr-inzn , can you please update the extension to v2 and please let me know if the issue persists?
Thanks!

**Comment by opr-inzn** [comment]
Hey @connordavenport, sorry, my bad! That fixed it!
