### ISSUE TITLE
Cannot open ThemeManager in RF4

### ISSUE THREAD

**Issue by roberto-arista** [connordavenport/Theme-Manager#7]
Here's the output

```plaintext
/Users/robertoarista/Library/Application Support/RoboFont/plugins/ThemeManager.roboFontExt/lib/ThemeManager.py:517: DeprecationWarning: The readPlist function is deprecated, use load() instead
  themeData = readPlist(plistPath)
Traceback (most recent call last):
  File "ThemeManager.py", line 629, in <module>
    OpenWindow(ThemeManager)
  File "/Users/robertoarista/Documents/Repositories/RF_virtualApp/roboFont.test/roboFont.source/robofont/lib/scripting/nameSpaceCallbacks.py", line 51, in OpenWindow
    scriptingWindowController[key] = controller(*args, **kwargs)
  File "ThemeManager.py", line 155, in __init__
    self.makeBackupTheme()
  File "ThemeManager.py", line 545, in makeBackupTheme
    data = dataType(data)
TypeError: 'NoneType' object is not iterable
```

👋

**Comment by connordavenport** [comment]
Hey @roberto-arista, what build is this occurring in? I can't recreate this in `Version 4.0b (build 2106021419)`

**Comment by roberto-arista** [comment]
I am on a dev build `2107081004 `

**Comment by roberto-arista** [comment]
maybe some keys changed recently? ping @typemytype

**Comment by roberto-arista** [comment]
for example: `getDefault("glyphViewOffCurvePointsStroke")` returns `None`

**Comment by connordavenport** [comment]
Hmm, I have no idea how a key would have been set to None. While I look into this, you can set a theme file using this script:

```
from plistlib import readPlist
from mojo.UI import getDefault, setDefault
from lib.tools.notifications import PostNotification

path = "path/to/file.roboFontTheme"
themeData = readPlist(path)
for key,val in themeData.items():
    setDefault(key, val)
PostNotification("doodle.preferencesChanged")
```

**Comment by AndreTeixeira30** [comment]
Hello there! I'm actually having a similar issue with this extension. I'm using RF 4.1 and ThemeManager version is 1.0.2

Bellow, there is the message error that I got

```
/Users/andreteixeira/Library/Application Support/RoboFont/plugins/ThemeManager.roboFontExt/lib/ThemeManager.py:517: DeprecationWarning: The readPlist function is deprecated, use load() instead
Traceback (most recent call last):
  File "ThemeManager.py", line 629, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 51, in OpenWindow
  File "ThemeManager.py", line 155, in __init__
  File "ThemeManager.py", line 545, in makeBackupTheme
TypeError: 'NoneType' object is not iterable

```

**Comment by connordavenport** [comment]
Thanks for the error report @AndreTeixeira30. I am looking into this right now, AFAIK RF4 changed some keys so I need to work on making the tool backwards compatible with older themes. I hope to fix this soon, sorry!

**Comment by typemytype** [comment]
a quick look: `data = getDefault(key)` could be `None` if the key is not available or not set... 
so I would advise to test if `data is not None` and just skip or change the `THEMEKEYS` information

**Comment by ryanbugden** [comment]
Hi! I'm getting a similar error:
```
Traceback (most recent call last):
  File "ThemeManager.py", line 635, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 52, in OpenWindow
  File "ThemeManager.py", line 156, in __init__
  File "ThemeManager.py", line 551, in makeBackupTheme
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by connordavenport** [comment]
Ah, I am going to push a huge update right now — Its essentially a complete rewrite of TM so I am hoping this fixes this bug too.

**Comment by connordavenport** [comment]
Okay maybe not right now, I need to fix a bug in the custom glyph view but soon. I had to rewrite the glyphView from defconAppKit in Merz so its kinda unstable haha
