### ISSUE TITLE
Traceback on Ventura

### ISSUE THREAD

**Issue by LettError** [connordavenport/Theme-Manager#8]
```
/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/py23.py:6: DeprecationWarning: The py23 module has been deprecated and will be removed. Please update your code.
/Users/<user>/Library/Application Support/RoboFont/plugins/ThemeManager.roboFontExt/lib/ThemeManager.py:517: DeprecationWarning: The readPlist function is deprecated, use load() instead
Traceback (most recent call last):
  File "ThemeManager.py", line 629, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 51, in OpenWindow
  File "ThemeManager.py", line 155, in _init
  File "ThemeManager.py", line 545, in makeBackupTheme
TypeError: 'NoneType' object is not iterable
```

**Comment by connordavenport** [comment]
Thanks @LettError, I am going to look into this!

**Comment by LettError** [comment]
(may not be a Ventura issue - it is just one of the ways the machine I observed was different from mine)

**Comment by connordavenport** [comment]
Someone did bring this up a few months back and I think its a RF4 issue also and I might need to reconfigure the reading of the `plist` file

**Comment by connordavenport** [comment]
Hey @LettError , this issue should be resolved via the most recent update with help from @frankrolf !

**Comment by LettError** [comment]
Ooh! Happy to report it Thememanager works in Version 4.4b (build 2212022233)
